// import * as create_ticket_menu from "../../../assets/create_ticket_menu.png"
// import { LazyLoadImage } from "react-lazy-load-image-component";
let tickets_q_and_a=[
    {
        title:"How to create a ticket?",
        content:(<>
            <div>
                <ol>
                    <li><p>1. Firstly click in left menu on  <strong>Tickets</strong>/<strong>Create Ticket</strong></p></li>
                    <li><p>2. Complete the required fields and click <strong>Submit</strong></p></li>
                    <li><p>3. You will be redirected to the ticket page</p></li>
                    <li><p><strong>Side note</strong>: You can also view your created tickets from <strong>Tickets</strong>/<strong>My Tickets</strong></p></li>
                </ol>
            </div>
        </>),
    },{
        title:"How to get a free ticket assigned to me?",
        content:(<>
            <p>You can view your assigned tickets from <strong>Tickets</strong>/<strong>Free Tickets</strong></p>
        </>)
    
    },{
    title:"How to view my tickets that requires my answers?",
    content:(<>
        <p>You can view your assigned tickets from <strong>Tickets</strong>/<strong>In Pending Tickets</strong></p>
    </>)
},{
    title:"What is workflow?",
    content:(<>
        <p>The workflow is very simple, either a client can create a ticket via the public web application or via sending an email to the support email box, configured by your administrator.
        The ticket will be created and assigned to the client. The client can then view the ticket and reply to it either from the web application or via email by entering the ticket code 
        automatically generated by the system. The ticket will be create and showed in <strong>Tickets</strong>/<strong>Free Tickets</strong>.</p> 
        <p>
           From <strong>Tickets</strong>/<strong>Free Tickets</strong> you can assign a ticket to youself, by pressing the <strong>Assign to me</strong> button. By clicking on the button you will be redirected to the ticket page.
           In ticket page you can either reply to the ticket or view the ticket and also change the status of the ticket. Every message send by you will be shown in the <strong>Messages</strong> section and also send via email to the client.
        </p>
        
    </>)

},
]

export default tickets_q_and_a;